# Minimal Agent Configuration Example
# This shows the bare minimum configuration Arc needs to profile an agent

model: "gpt-4.1"
temperature: 0.7
system_prompt: "You are a helpful assistant"
tools: ["web_search", "calculator"]